server:
  port: 5000

amazon:
  associateId: habuma-20

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: false

logging.level:
  org.springframework.security: DEBUG
  org.hibernate:
    SQL: DEBUG
    type: TRACE
#    type.descriptor.sql.BasicBinder: TRACE
spring.jpa.properties.hibernate:
  show_sql: true
  use_sql_comments: false
  format_sql: false
  type: trace

management:
  context-path: /actuator
