server:
  port: 5000

amazon:
  associateId: habuma-20

spring:
  thymeleaf:
    cache: false

logging:
  file: readingList.log
  level:
    org.springframework.security: DEBUG

management:
  context-path: /actuator

---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://localhost:5432/readinglist
    username: pivotal
    password: steal13kittens
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none


