server:
  port: 5000

amazon:
  associateId: habuma-20

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: false

logging:
  file: readingList.log
  level:
    org.springframework.security: DEBUG

management:
  context-path: /actuator


